-- Query A — The Removal List (Read-Only)
-- WRITES - review before running
--
-- GENERATED from 590-proquest-purchase-removal-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

WITH ebk AS (                        -- collapse the item side: one row per bib
        SELECT DISTINCT [bib#]
        FROM item_with_title
        WHERE collection = 'EBK'
),
qual AS (
        SELECT
            e.[bib#],
            CASE WHEN EXISTS (       -- one 590 holding BOTH words
                     SELECT 1 FROM bib s
                     WHERE s.[bib#] = e.[bib#] AND s.tag = '590'
                       AND s.text LIKE '%ProQuest%' AND s.text LIKE '%purchase%')
                 THEN 'SAME_ROW' ELSE 'CROSS_ROW' END AS match_type,
            CASE WHEN EXISTS (       -- record also has a DDA note
                     SELECT 1 FROM bib d
                     WHERE d.[bib#] = e.[bib#] AND d.tag = '590'
                       AND d.text COLLATE Latin1_General_CS_AS LIKE '%DDA%')
                 THEN 'Y' ELSE '' END AS has_dda,
            CASE WHEN EXISTS (       -- record also has a subscription note
                     SELECT 1 FROM bib sub
                     WHERE sub.[bib#] = e.[bib#] AND sub.tag = '590'
                       AND sub.text LIKE '%subscription%')
                 THEN 'Y' ELSE '' END AS has_subscription
        FROM ebk e
        WHERE EXISTS (               -- some 590 contains ProQuest
                SELECT 1 FROM bib p
                WHERE p.[bib#] = e.[bib#] AND p.tag = '590'
                  AND p.text LIKE '%ProQuest%')
          AND EXISTS (               -- some 590 contains purchase
                SELECT 1 FROM bib u
                WHERE u.[bib#] = e.[bib#] AND u.tag = '590'
                  AND u.text LIKE '%purchase%')
)
SELECT
    q.[bib#]           AS [bib#],
    t.title            AS [title],
    q.match_type       AS [match_type],
    q.has_dda          AS [has_dda],
    q.has_subscription AS [has_subscription]
FROM qual q
OUTER APPLY (                        -- 245$a title (see "Title parsing" below)
    SELECT TOP 1
        RTRIM(CASE WHEN RIGHT(RTRIM(raw.sa), 1) IN ('/',':',';',',','=','.')
                   THEN RTRIM(LEFT(RTRIM(raw.sa), LEN(RTRIM(raw.sa)) - 1))
                   ELSE RTRIM(raw.sa) END) AS title
    FROM bib t245
    CROSS APPLY (SELECT CHARINDEX(CHAR(31) + 'a', t245.text) AS pa) m
    CROSS APPLY (SELECT NULLIF(CHARINDEX(CHAR(31), t245.text, m.pa + 2), 0) AS nxt,
                        NULLIF(CHARINDEX(CHAR(30), t245.text, m.pa + 2), 0) AS fend) d
    CROSS APPLY (SELECT SUBSTRING(
                     t245.text, m.pa + 2,
                     COALESCE((SELECT MIN(v) FROM (VALUES (d.nxt),(d.fend)) x(v)),
                              LEN(t245.text) + 1) - (m.pa + 2)) AS sa) raw
    WHERE t245.[bib#] = q.[bib#] AND t245.tag = '245' AND m.pa > 0
    ORDER BY t245.tagord             -- lowest-tagord 245 segment
) t
ORDER BY q.has_subscription DESC, q.match_type, q.[bib#];
