-- Optional notes_590 column (SQL Server 2017+, compat 110+ only)
-- READ-ONLY
--
-- GENERATED from 590-proquest-purchase-removal-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

OUTER APPLY (                        -- the matching 590(s), collapsed to one cell
    SELECT STRING_AGG(pp.text, ' | ') WITHIN GROUP (ORDER BY pp.tagord) AS notes_590
    FROM bib pp
    WHERE pp.[bib#] = q.[bib#] AND pp.tag = '590'
      AND (pp.text LIKE '%ProQuest%' OR pp.text LIKE '%purchase%')
) n
