-- Query B — Detail / Verification (Read-Only)
-- WRITES - review before running
--
-- GENERATED from 590-proquest-purchase-removal-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

WITH ebk AS (
        SELECT DISTINCT [bib#] FROM item_with_title WHERE collection = 'EBK'
),
qual AS (
        SELECT e.[bib#],
            CASE WHEN EXISTS (
                     SELECT 1 FROM bib s
                     WHERE s.[bib#] = e.[bib#] AND s.tag = '590'
                       AND s.text LIKE '%ProQuest%' AND s.text LIKE '%purchase%')
                 THEN 'SAME_ROW' ELSE 'CROSS_ROW' END AS match_type
        FROM ebk e
        WHERE EXISTS (SELECT 1 FROM bib p WHERE p.[bib#] = e.[bib#]
                        AND p.tag = '590' AND p.text LIKE '%ProQuest%')
          AND EXISTS (SELECT 1 FROM bib u WHERE u.[bib#] = e.[bib#]
                        AND u.tag = '590' AND u.text LIKE '%purchase%')
)
SELECT q.[bib#] AS [bib#], q.match_type AS [match_type],
       b.tag AS [tag], b.text AS [text]
FROM qual q
INNER JOIN bib b ON b.[bib#] = q.[bib#] AND b.tag = '590'
ORDER BY q.[bib#], b.tagord;
