-- Query C — Counts (Read-Only)
-- WRITES - review before running
--
-- GENERATED from 590-proquest-purchase-removal-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

WITH ebk AS (
        SELECT DISTINCT [bib#] FROM item_with_title WHERE collection = 'EBK'
),
qual AS (
        SELECT e.[bib#],
            CASE WHEN EXISTS (
                     SELECT 1 FROM bib s
                     WHERE s.[bib#] = e.[bib#] AND s.tag = '590'
                       AND s.text LIKE '%ProQuest%' AND s.text LIKE '%purchase%')
                 THEN 'SAME_ROW' ELSE 'CROSS_ROW' END AS match_type,
            CASE WHEN EXISTS (SELECT 1 FROM bib d WHERE d.[bib#] = e.[bib#]
                     AND d.tag = '590'
                     AND d.text COLLATE Latin1_General_CS_AS LIKE '%DDA%')
                 THEN 1 ELSE 0 END AS has_dda,
            CASE WHEN EXISTS (SELECT 1 FROM bib sub WHERE sub.[bib#] = e.[bib#]
                     AND sub.tag = '590' AND sub.text LIKE '%subscription%')
                 THEN 1 ELSE 0 END AS has_sub
        FROM ebk e
        WHERE EXISTS (SELECT 1 FROM bib p WHERE p.[bib#] = e.[bib#]
                        AND p.tag = '590' AND p.text LIKE '%ProQuest%')
          AND EXISTS (SELECT 1 FROM bib u WHERE u.[bib#] = e.[bib#]
                        AND u.tag = '590' AND u.text LIKE '%purchase%')
)
SELECT
    match_type       AS [match_type],
    COUNT(*)         AS [bibs],
    SUM(has_dda)     AS [with_dda_590],
    SUM(has_sub)     AS [with_subscription_590]
FROM qual
GROUP BY match_type
WITH ROLLUP
ORDER BY GROUPING(match_type), match_type;
