-- Coverage note (item-side EBK definition)
-- READ-ONLY
--
-- GENERATED from 590-proquest-purchase-removal-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SELECT COUNT(*) AS [ebk_049_bibs_with_no_ebk_item]
FROM (SELECT DISTINCT b049.[bib#] FROM bib b049
      WHERE b049.tag = '049' AND b049.text LIKE '%EBK%'
        AND EXISTS (SELECT 1 FROM bib p WHERE p.[bib#] = b049.[bib#]
                    AND p.tag = '590' AND p.text LIKE '%ProQuest%')
        AND EXISTS (SELECT 1 FROM bib u WHERE u.[bib#] = b049.[bib#]
                    AND u.tag = '590' AND u.text LIKE '%purchase%')) z
WHERE NOT EXISTS (SELECT 1 FROM item_with_title i
                  WHERE i.[bib#] = z.[bib#] AND i.collection = 'EBK');
