-- Building the delete-list table (after approval)
-- WRITES - review before running
--
-- GENERATED from 590-proquest-purchase-removal-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

IF OBJECT_ID('dbo.ProQuest_Purchase_DeleteList', 'U') IS NOT NULL
    DROP TABLE dbo.ProQuest_Purchase_DeleteList;
GO
CREATE TABLE dbo.ProQuest_Purchase_DeleteList (
    [bib#] INT NOT NULL
        CONSTRAINT PK_ProQuest_Purchase_DeleteList PRIMARY KEY
);
GO
INSERT INTO dbo.ProQuest_Purchase_DeleteList ([bib#]) VALUES
(5384390),
(5384391);   -- … one row per approved bib#; see batching note below
GO
-- Verify against the approved count before handing off.
SELECT COUNT(*) AS [rows_loaded] FROM dbo.ProQuest_Purchase_DeleteList;
GO
