-- Running the batch delete (Horizon KillBib)
-- READ-ONLY
--
-- GENERATED from 590-proquest-purchase-removal-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SELECT i.location AS missing_location_code,
       COUNT(*) AS item_count, COUNT(DISTINCT i.[bib#]) AS bib_count
FROM item i
JOIN dbo.ProQuest_Purchase_DeleteList d ON d.[bib#] = i.[bib#]
LEFT JOIN location l ON l.location = i.location
WHERE l.location IS NULL
GROUP BY i.location;
