-- Appendix: MUPO / SUPO and the duplicate-record cleanup (deferred)
-- READ-ONLY
--
-- GENERATED from 590-proquest-purchase-removal-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SELECT tag, COUNT(*) AS hits
FROM bib
WHERE text LIKE '%MUPO%' OR text LIKE '%SUPO%'
GROUP BY tag ORDER BY hits DESC;
