-- The Report (Read-Only)
-- READ-ONLY
--
-- GENERATED from 590-ebk-049-dda-not-purchased-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SELECT
    b.[bib#] AS [bib#],
    t.title  AS [title],
    b.text   AS [text]
FROM bib b
OUTER APPLY (
    SELECT TOP 1
        -- strip one trailing ISBD punctuation mark (e.g. " /", " :") + spaces
        RTRIM(CASE WHEN RIGHT(RTRIM(raw.sa), 1) IN ('/',':',';',',','=','.')
                   THEN RTRIM(LEFT(RTRIM(raw.sa), LEN(RTRIM(raw.sa)) - 1))
                   ELSE RTRIM(raw.sa) END) AS title
    FROM bib t245
    CROSS APPLY (SELECT CHARINDEX(CHAR(31) + 'a', t245.text) AS pa) m
    CROSS APPLY (SELECT NULLIF(CHARINDEX(CHAR(31), t245.text, m.pa + 2), 0) AS nxt,
                        NULLIF(CHARINDEX(CHAR(30), t245.text, m.pa + 2), 0) AS fend) e
    CROSS APPLY (SELECT SUBSTRING(
                     t245.text, m.pa + 2,
                     COALESCE((SELECT MIN(v) FROM (VALUES (e.nxt),(e.fend)) x(v)),
                              LEN(t245.text) + 1) - (m.pa + 2)) AS sa) raw
    WHERE t245.[bib#] = b.[bib#]
      AND t245.tag = '245'
      AND m.pa > 0
    ORDER BY t245.tagord            -- lowest-tagord 245 segment
) t
WHERE b.tag = '590'
  -- case-sensitive: the subfield delimiter code 'd' ($d "Date…") next to
  -- content beginning "Da…" forms the literal 'dDa', which a case-insensitive
  -- LIKE '%DDA%' falsely matches. MARC subfield codes are lowercase, so an
  -- uppercase 'DDA' can never be forged at a code/content boundary.
  AND b.text COLLATE Latin1_General_CS_AS LIKE '%DDA%'
  AND EXISTS (                       -- bib has a 049 marking it EBK
        SELECT 1 FROM bib e049
        WHERE e049.[bib#] = b.[bib#]
          AND e049.tag = '049'
          AND e049.text LIKE '%EBK%'
      )
  AND NOT EXISTS (                   -- bib has NO 590 containing 'purchase'
        SELECT 1 FROM bib bp
        WHERE bp.[bib#] = b.[bib#]
          AND bp.tag = '590'
          AND bp.text LIKE '%purchase%'
      )
ORDER BY b.[bib#], b.tagord;
