-- Query the check uses
-- READ-ONLY
--
-- GENERATED from 590-proquest-new-by-creator-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SELECT TOP 5
       bc.[bib#] AS [bib#],
       DATEADD(day, bc.create_date, CAST('1970-01-01' AS DATE)) AS [created]
FROM bib_control bc
WHERE bc.create_user = 'CATALOGER'
  AND bc.create_date >= DATEDIFF(day, '1970-01-01', '2026-02-25')
  AND NOT EXISTS (
        SELECT 1 FROM bib p
        WHERE p.[bib#] = bc.[bib#]
          AND p.tag = '590'
          AND p.text LIKE '%ProQuest%')
ORDER BY bc.create_date DESC;
