-- The per-day form (slower, more detail)
-- READ-ONLY
--
-- GENERATED from 590-proquest-new-by-creator-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SELECT d.[created],
       COUNT(*)                 AS [total],
       SUM(d.is_pq)             AS [proquest],
       COUNT(*) - SUM(d.is_pq)  AS [not_proquest]
FROM (
    SELECT DATEADD(day, bc.create_date, CAST('1970-01-01' AS DATE)) AS [created],
           CASE WHEN EXISTS (SELECT 1 FROM bib p
                             WHERE p.[bib#] = bc.[bib#]
                               AND p.tag = '590'
                               AND p.text LIKE '%ProQuest%')
                THEN 1 ELSE 0 END AS is_pq
    FROM bib_control bc
    WHERE bc.create_user = 'CATALOGER'
      AND bc.create_date >= DATEDIFF(day, '1970-01-01', '2026-02-01')
) d
GROUP BY d.[created]
ORDER BY d.[created];
