-- Query 0 — Verify epoch and operator spelling
-- READ-ONLY
--
-- GENERATED from 590-proquest-new-by-creator-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- 0a. Does the assumed 1970-01-01 epoch decode to sane dates?
SELECT
    MAX(create_date) AS [max_day_number],
    DATEADD(day, MAX(create_date), CAST('1970-01-01' AS DATE)) AS [decodes_to],
    MIN(create_date) AS [min_day_number],
    DATEADD(day, MIN(create_date), CAST('1970-01-01' AS DATE)) AS [min_decodes_to]
FROM bib_control;

-- 0b. Who created records on the target day, and how many?
SELECT
    bc.create_user AS [create_user],
    COUNT(*)       AS [bibs_created]
FROM bib_control bc
WHERE bc.create_date = DATEDIFF(day, '1970-01-01', '2026-08-25')
GROUP BY bc.create_user
ORDER BY [bibs_created] DESC;
