-- Query A — The Report (Read-Only)
-- READ-ONLY
--
-- GENERATED from 590-proquest-new-by-creator-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SELECT
    bc.[bib#]      AS [bib#],
    t.title        AS [title],
    bc.create_user AS [create_user],
    DATEADD(day, bc.create_date, CAST('1970-01-01' AS DATE)) AS [create_date]
FROM bib_control bc
OUTER APPLY (                        -- 245$a title (see "Title parsing" below)
    SELECT TOP 1
        RTRIM(CASE WHEN RIGHT(RTRIM(raw.sa), 1) IN ('/',':',';',',','=','.')
                   THEN RTRIM(LEFT(RTRIM(raw.sa), LEN(RTRIM(raw.sa)) - 1))
                   ELSE RTRIM(raw.sa) END) AS title
    FROM bib t245
    CROSS APPLY (SELECT CHARINDEX(CHAR(31) + 'a', t245.text) AS pa) m
    CROSS APPLY (SELECT NULLIF(CHARINDEX(CHAR(31), t245.text, m.pa + 2), 0) AS nxt,
                        NULLIF(CHARINDEX(CHAR(30), t245.text, m.pa + 2), 0) AS fend) d
    CROSS APPLY (SELECT SUBSTRING(
                     t245.text, m.pa + 2,
                     COALESCE((SELECT MIN(v) FROM (VALUES (d.nxt),(d.fend)) x(v)),
                              LEN(t245.text) + 1) - (m.pa + 2)) AS sa) raw
    WHERE t245.[bib#] = bc.[bib#] AND t245.tag = '245' AND m.pa > 0
    ORDER BY t245.tagord             -- lowest-tagord 245 segment
) t
WHERE bc.create_user = 'CATALOGER'
  AND bc.create_date = DATEDIFF(day, '1970-01-01', '2026-08-25')
  AND EXISTS (                       -- some 590 contains ProQuest
        SELECT 1 FROM bib p
        WHERE p.[bib#] = bc.[bib#]
          AND p.tag = '590'
          AND p.text LIKE '%ProQuest%')
ORDER BY bc.[bib#];
