-- Query B — Detail / Verification (Read-Only)
-- READ-ONLY
--
-- GENERATED from 590-proquest-new-by-creator-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SELECT
    bc.[bib#]      AS [bib#],
    bc.create_user AS [create_user],
    b.tag          AS [tag],
    b.text         AS [text]
FROM bib_control bc
INNER JOIN bib b
        ON b.[bib#] = bc.[bib#]
       AND b.tag = '590'
WHERE bc.create_user = 'CATALOGER'
  AND bc.create_date = DATEDIFF(day, '1970-01-01', '2026-08-25')
  AND EXISTS (
        SELECT 1 FROM bib p
        WHERE p.[bib#] = bc.[bib#]
          AND p.tag = '590'
          AND p.text LIKE '%ProQuest%')
ORDER BY bc.[bib#], b.tagord;
