-- Step 0 — Find the staff principal
-- READ-ONLY
--
-- GENERATED from 590-proquest-new-by-creator-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SELECT name        AS [principal],
       type_desc   AS [type]
FROM sys.database_principals
WHERE type IN ('R','G','U')          -- roles, Windows groups, users
  AND name NOT IN ('public','guest','INFORMATION_SCHEMA','sys')
  AND is_fixed_role = 0
ORDER BY type_desc, name;
