-- Step 1 — Create the table
-- WRITES - review before running
--
-- GENERATED from 590-proquest-new-by-creator-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

IF OBJECT_ID('dbo.ProQuest_CAT_20260825_DeleteList', 'U') IS NOT NULL
    DROP TABLE dbo.ProQuest_CAT_20260825_DeleteList;
GO

CREATE TABLE dbo.ProQuest_CAT_20260825_DeleteList (
    [bib#] INT NOT NULL
        CONSTRAINT PK_ProQuest_CAT_20260825_DeleteList
            PRIMARY KEY CLUSTERED ([bib#])
);
GO
