-- Step 2 — Populate it, count-checked before commit
-- WRITES - review before running
--
-- GENERATED from 590-proquest-new-by-creator-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

BEGIN TRANSACTION;

INSERT INTO dbo.ProQuest_CAT_20260825_DeleteList ([bib#])
SELECT bc.[bib#]
FROM bib_control bc
WHERE bc.create_user = 'CATALOGER'
  AND bc.create_date = DATEDIFF(day, '1970-01-01', '2026-08-25')
  AND EXISTS (                       -- some 590 contains ProQuest
        SELECT 1 FROM bib p
        WHERE p.[bib#] = bc.[bib#]
          AND p.tag = '590'
          AND p.text LIKE '%ProQuest%');

SELECT @@ROWCOUNT AS [rows_inserted];

-- Compare rows_inserted against the Query C count and the reviewed CSV.
-- COMMIT only if all three agree.
-- COMMIT TRANSACTION;
-- ROLLBACK TRANSACTION;
