-- Step 3 — Grant read access to staff
-- WRITES - review before running
--
-- GENERATED from 590-proquest-new-by-creator-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

GRANT SELECT ON dbo.ProQuest_CAT_20260825_DeleteList TO [<staff-principal>];
GO
