-- Step 4 — Verify before handing it off
-- READ-ONLY
--
-- GENERATED from 590-proquest-new-by-creator-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- 1. Row count must equal Query C and the reviewed CSV
SELECT COUNT(*) AS [rows_loaded]
FROM dbo.ProQuest_CAT_20260825_DeleteList;

-- 2. The key exists, is clustered and unique
SELECT i.name AS [index_name], i.type_desc, i.is_unique, i.is_primary_key
FROM sys.indexes i
WHERE i.object_id = OBJECT_ID('dbo.ProQuest_CAT_20260825_DeleteList')
  AND i.type > 0;

-- 3. The grant landed on the intended principal
SELECT dp.name            AS [principal],
       dp.type_desc       AS [principal_type],
       p.permission_name  AS [permission],
       p.state_desc       AS [state]
FROM sys.database_permissions p
INNER JOIN sys.database_principals dp
        ON dp.principal_id = p.grantee_principal_id
WHERE p.major_id = OBJECT_ID('dbo.ProQuest_CAT_20260825_DeleteList');
