-- Use the wrapper
-- READ-ONLY
--
-- GENERATED from 590-proquest-new-by-creator-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SELECT COUNT(*) AS [bib_control] FROM bib_control WHERE [bib#] = <trial-bib#>;  -- 0
SELECT COUNT(*) AS [bib]         FROM bib         WHERE [bib#] = <trial-bib#>;  -- 0
SELECT COUNT(*) AS [item]        FROM item        WHERE [bib#] = <trial-bib#>;  -- 0 with /k
