-- Afterwards
-- READ-ONLY
--
-- GENERATED from 590-proquest-new-by-creator-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Every listed bib should be gone
SELECT COUNT(*) AS [still_present]
FROM bib_control bc
INNER JOIN dbo.ProQuest_CAT_20260825_DeleteList d ON d.[bib#] = bc.[bib#];
