-- Step 6 — Verify, then clean up
-- WRITES - review before running
--
-- GENERATED from 590-proquest-new-by-creator-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Fail in 10s rather than hanging on a lock left by an interrupted run.
SET LOCK_TIMEOUT 10000;

-- What is about to be dropped, and how many rows each holds.
SELECT t.name AS [table], SUM(p.rows) AS [rows]
FROM sys.tables t
INNER JOIN sys.partitions p
        ON p.object_id = t.object_id AND p.index_id IN (0,1)
WHERE t.name IN ('PQ_CAT_20260825_DeleteList',
                 'ProQuest_CAT_20260825_DeleteList',
                 'ProQuest_CAT_20260825_DeleteList_2',
                 'KillBibProbe')
GROUP BY t.name
ORDER BY t.name;
GO

SET LOCK_TIMEOUT 10000;

IF OBJECT_ID('dbo.PQ_CAT_20260825_DeleteList','U') IS NOT NULL
BEGIN DROP TABLE dbo.PQ_CAT_20260825_DeleteList;        PRINT 'dropped PQ_CAT_20260825_DeleteList'; END
ELSE PRINT 'PQ_CAT_20260825_DeleteList not present';

IF OBJECT_ID('dbo.ProQuest_CAT_20260825_DeleteList','U') IS NOT NULL
BEGIN DROP TABLE dbo.ProQuest_CAT_20260825_DeleteList;  PRINT 'dropped ProQuest_CAT_20260825_DeleteList'; END
ELSE PRINT 'ProQuest_CAT_20260825_DeleteList not present';

IF OBJECT_ID('dbo.ProQuest_CAT_20260825_DeleteList_2','U') IS NOT NULL
BEGIN DROP TABLE dbo.ProQuest_CAT_20260825_DeleteList_2; PRINT 'dropped ProQuest_CAT_20260825_DeleteList_2'; END
ELSE PRINT 'ProQuest_CAT_20260825_DeleteList_2 not present';

IF OBJECT_ID('dbo.KillBibProbe','U') IS NOT NULL
BEGIN DROP TABLE dbo.KillBibProbe;                       PRINT 'dropped KillBibProbe'; END
ELSE PRINT 'KillBibProbe not present';
GO

-- Confirm nothing is left.
SELECT name FROM sys.tables
WHERE name LIKE '%DeleteList%' OR name = 'KillBibProbe'
ORDER BY name;
