-- Alternative: SELECT INTO (only under SIMPLE / BULK_LOGGED)
-- WRITES - review before running
--
-- GENERATED from 590-proquest-new-by-creator-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SELECT bc.[bib#]
INTO dbo.ProQuest_CAT_20260825_DeleteList
FROM bib_control bc
WHERE /* ...same predicate... */;

ALTER TABLE dbo.ProQuest_CAT_20260825_DeleteList
    ALTER COLUMN [bib#] INT NOT NULL;          -- required: SELECT INTO inherits NULL
GO
ALTER TABLE dbo.ProQuest_CAT_20260825_DeleteList
    ADD CONSTRAINT PK_ProQuest_CAT_20260825_DeleteList
        PRIMARY KEY CLUSTERED ([bib#]);
