-- Alternative: SELECT INTO (only under SIMPLE / BULK_LOGGED)
-- READ-ONLY
--
-- GENERATED from 590-proquest-new-by-creator-report/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SELECT name AS [database], recovery_model_desc AS [recovery_model]
FROM sys.databases
WHERE database_id = DB_ID();
