-- 1b. Candidate list
-- READ-ONLY
--
-- GENERATED from db-scratch-table-cleanup/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

DECLARE @VendorCutoff datetime = '2026-01-01 00:00:00';   -- from step 1a

SELECT
    t.name                                   AS [table_name],
    CONVERT(char(19), t.create_date, 120)    AS [created],
    CONVERT(char(19), t.modify_date, 120)    AS [last_modified],
    ISNULL(SUM(p.rows), 0)                   AS [rows],
    CAST(ROUND(SUM(a.total_pages) * 8.0 / 1024, 1) AS decimal(10,1)) AS [mb]
FROM sys.tables t
LEFT JOIN sys.partitions p
       ON p.object_id = t.object_id AND p.index_id IN (0,1)
LEFT JOIN sys.allocation_units a
       ON a.container_id = p.partition_id
WHERE t.is_ms_shipped = 0
  AND t.create_date > @VendorCutoff
GROUP BY t.name, t.create_date, t.modify_date
ORDER BY t.create_date;
