-- 1e. Vendor-signal check — 1c is not sufficient on its own
-- READ-ONLY
--
-- GENERATED from db-scratch-table-cleanup/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

DECLARE @VendorCutoff datetime = '2022-04-11 06:45:59';

SELECT
    t.name                                            AS [table_name],
    (SELECT COUNT(*) FROM sys.columns c
      WHERE c.object_id = t.object_id)                AS [columns],
    CASE WHEN EXISTS (SELECT 1 FROM sys.indexes i
                      WHERE i.object_id = t.object_id AND i.is_primary_key = 1)
         THEN 'YES' ELSE '' END                       AS [declared_pk],
    CASE WHEN EXISTS (SELECT 1 FROM sys.indexes i
                      WHERE i.object_id = t.object_id AND i.is_unique = 1)
         THEN 'yes' ELSE '' END                       AS [unique_index],
    -- Vendor tables are built from Horizon's user-defined types. A scratch
    -- table made by SELECT INTO inherits base types instead.
    (SELECT COUNT(*) FROM sys.columns c
     INNER JOIN sys.types ty ON ty.user_type_id = c.user_type_id
      WHERE c.object_id = t.object_id AND ty.is_user_defined = 1) AS [udt_columns]
FROM sys.tables t
WHERE t.is_ms_shipped = 0
  AND t.create_date > @VendorCutoff
ORDER BY [udt_columns] DESC, [columns] DESC, t.name;
