-- 1d. Generate the DROP script for review
-- READ-ONLY
--
-- GENERATED from db-scratch-table-cleanup/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

DECLARE @VendorCutoff datetime = '2026-01-01 00:00:00';

SELECT
    'IF OBJECT_ID(''dbo.' + t.name + ''',''U'') IS NOT NULL' +
    ' BEGIN DROP TABLE dbo.[' + t.name + ']; PRINT ''dropped ' + t.name + '''; END' +
    ' ELSE PRINT ''' + t.name + ' not present'';'   AS [drop_statement],
    ISNULL(SUM(p.rows), 0)                          AS [rows_it_holds]
FROM sys.tables t
LEFT JOIN sys.partitions p
       ON p.object_id = t.object_id AND p.index_id IN (0,1)
WHERE t.is_ms_shipped = 0
  AND t.create_date > @VendorCutoff
  -- Exclude anything step 1c flagged as depended upon:
  AND NOT EXISTS (SELECT 1 FROM sys.sql_expression_dependencies d
                  WHERE d.referenced_entity_name = t.name)
  AND NOT EXISTS (SELECT 1 FROM sys.foreign_keys fk
                  WHERE fk.referenced_object_id = t.object_id)
GROUP BY t.name
ORDER BY t.name;
