-- Verify
-- READ-ONLY
--
-- GENERATED from db-scratch-table-cleanup/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

DECLARE @VendorCutoff datetime = '2026-01-01 00:00:00';

SELECT COUNT(*) AS [candidates_remaining]
FROM sys.tables
WHERE is_ms_shipped = 0 AND create_date > @VendorCutoff;
