-- A backup is required before Step 2
-- WRITES - review before running
--
-- GENERATED from pref-setting-user-profile-test/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SELECT * INTO pref_setting_bak_20260922 FROM pref_setting;
