-- Step 0: Verify before you touch anything (read-only)
-- READ-ONLY
--
-- GENERATED from pref-setting-user-profile-test/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Q0a: Do both accounts exist, and do they share a preference group?
-- Every column below was looked up in horizon-schema/, not inferred.
SELECT u.user_id,
       u.user_name,
       u.[pref_group#],
       u.save_preferences,
       u.user_disabled,
       u.security_level
FROM user_id u
WHERE u.user_id IN ('CATALOGER', 'CATALOGER_T')
ORDER BY u.user_id;
