-- Step 0: Verify before you touch anything (read-only)
-- READ-ONLY
--
-- GENERATED from pref-setting-user-profile-test/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Q0b: What is actually being copied, broken out by group and category?
SELECT ps.[pref_group#],
       ps.pref_category,
       COUNT(*) AS [rows]
FROM pref_setting ps
WHERE ps.user_id = 'CATALOGER'
GROUP BY ps.[pref_group#], ps.pref_category
ORDER BY ps.[pref_group#], ps.pref_category;
