-- Step 0: Verify before you touch anything (read-only)
-- READ-ONLY
--
-- GENERATED from pref-setting-user-profile-test/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Q0c: Current row counts on both sides. Record these.
SELECT ps.user_id, COUNT(*) AS [pref_rows]
FROM pref_setting ps
WHERE ps.user_id IN ('CATALOGER', 'CATALOGER_T')
GROUP BY ps.user_id
ORDER BY ps.user_id;
