-- If the preference groups differ
-- WRITES - review before running
--
-- GENERATED from pref-setting-user-profile-test/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Variant of Step 2's INSERT. Use ONLY when the two accounts are in different
-- preference groups and the test account's group cannot be changed.
-- Replace 2 with the test account's actual pref_group# from Q0a.
INSERT INTO pref_setting (pref_category, [pref_group#], user_id, pref_id, pref_data)
SELECT ps.pref_category, 2, 'CATALOGER_T', ps.pref_id, ps.pref_data
FROM pref_setting ps
WHERE ps.user_id = 'CATALOGER';
