-- Step 1: The Audit
-- READ-ONLY
--
-- GENERATED from pref-setting-user-profile-test/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Every table and column below was looked up in horizon-schema/, not inferred.
SELECT 'will DELETE' AS [action],
       ps.pref_category,
       ps.[pref_group#],
       ps.user_id,
       ps.pref_id,
       ps.pref_data
FROM pref_setting ps
WHERE ps.user_id = 'CATALOGER_T'

UNION ALL

SELECT 'will INSERT as CATALOGER_T' AS [action],
       ps.pref_category,
       ps.[pref_group#],
       ps.user_id,
       ps.pref_id,
       ps.pref_data
FROM pref_setting ps
WHERE ps.user_id = 'CATALOGER'

ORDER BY [action], pref_category, [pref_group#], pref_id;
