-- Step 2: The Update
-- WRITES - review before running
--
-- GENERATED from pref-setting-user-profile-test/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

BEGIN TRANSACTION;

DELETE FROM pref_setting
WHERE user_id = 'CATALOGER_T';

SELECT @@ROWCOUNT AS [rows_deleted];    -- compare to the audit's "will DELETE"

INSERT INTO pref_setting (pref_category, [pref_group#], user_id, pref_id, pref_data)
SELECT ps.pref_category,
       ps.[pref_group#],
       'CATALOGER_T',
       ps.pref_id,
       ps.pref_data
FROM pref_setting ps
WHERE ps.user_id = 'CATALOGER';

SELECT @@ROWCOUNT AS [rows_inserted];   -- compare to the audit's "will INSERT"

-- Both counts match the audit:
-- COMMIT TRANSACTION;
-- Either count is different:
-- ROLLBACK TRANSACTION;
