-- 4a. Are the two accounts comparable?
-- READ-ONLY
--
-- GENERATED from pref-setting-user-profile-test/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Read-only. Every column looked up in horizon-schema/, not inferred.
SELECT u.user_id,
       u.user_name,
       u.[pref_group#],
       u.save_preferences,
       u.user_disabled
FROM user_id u
WHERE u.user_id IN ('CATALOGER', 'CATALOGER_T')
ORDER BY u.user_id;
