-- 4b. Which preference groups do their rows actually sit in?
-- READ-ONLY
--
-- GENERATED from pref-setting-user-profile-test/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Read-only.
SELECT ps.user_id,
       ps.[pref_group#],
       COUNT(*) AS [rows]
FROM pref_setting ps
WHERE ps.user_id IN ('CATALOGER', 'CATALOGER_T')
GROUP BY ps.user_id, ps.[pref_group#]
ORDER BY ps.user_id, ps.[pref_group#];
