-- 4c. The diff
-- READ-ONLY
--
-- GENERATED from pref-setting-user-profile-test/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Read-only. Shows rows present on one side only, and rows whose value differs.
SELECT
    COALESCE(a.pref_category, b.pref_category) AS [pref_category],
    COALESCE(a.[pref_group#], b.[pref_group#]) AS [pref_group#],
    COALESCE(a.pref_id, b.pref_id)             AS [pref_id],
    CASE WHEN a.user_id IS NULL THEN 'only on the test login'
         WHEN b.user_id IS NULL THEN 'only on the real account'
         ELSE 'value differs' END              AS [difference],
    a.pref_data                                AS [real_value],
    b.pref_data                                AS [test_value],
    DATALENGTH(a.pref_data)                    AS [real_bytes],
    DATALENGTH(b.pref_data)                    AS [test_bytes]
FROM      (SELECT pref_category, [pref_group#], user_id, pref_id, pref_data
           FROM pref_setting WHERE user_id = 'CATALOGER')   a
FULL OUTER JOIN
          (SELECT pref_category, [pref_group#], user_id, pref_id, pref_data
           FROM pref_setting WHERE user_id = 'CATALOGER_T') b
       ON  b.pref_category = a.pref_category
       AND b.pref_id       = a.pref_id
       AND (b.[pref_group#] = a.[pref_group#]
            OR (b.[pref_group#] IS NULL AND a.[pref_group#] IS NULL))
WHERE a.user_id IS NULL
   OR b.user_id IS NULL
   OR (a.pref_data IS     NULL AND b.pref_data IS NOT NULL)
   OR (a.pref_data IS NOT NULL AND b.pref_data IS     NULL)
   OR a.pref_data COLLATE Latin1_General_BIN
   <> b.pref_data COLLATE Latin1_General_BIN
   OR DATALENGTH(a.pref_data) <> DATALENGTH(b.pref_data)
ORDER BY [pref_category], [pref_group#], [pref_id];
