-- 4d. Hunt the corruption directly
-- READ-ONLY
--
-- GENERATED from pref-setting-user-profile-test/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Read-only. Structurally suspicious preference values on the real account.
SELECT
    ps.pref_category,
    ps.[pref_group#],
    ps.pref_id,
    ps.pref_data,
    DATALENGTH(ps.pref_data) AS [bytes],
    CASE
        WHEN ps.pref_data COLLATE Latin1_General_BIN LIKE '%[^ -~]%'
             THEN 'contains control or high-byte characters'
        WHEN DATALENGTH(ps.pref_data) = 255
             THEN 'exactly 255 bytes - possibly truncated'
        WHEN DATALENGTH(ps.pref_data)
          <> DATALENGTH(LTRIM(RTRIM(ps.pref_data)))
             THEN 'leading or trailing whitespace'
        ELSE ''
    END AS [why_suspicious]
FROM pref_setting ps
WHERE ps.user_id = 'CATALOGER'
  AND ps.pref_data IS NOT NULL
  AND (ps.pref_data COLLATE Latin1_General_BIN LIKE '%[^ -~]%'
       OR DATALENGTH(ps.pref_data) = 255
       OR DATALENGTH(ps.pref_data) <> DATALENGTH(LTRIM(RTRIM(ps.pref_data))))
ORDER BY [why_suspicious], ps.pref_category, ps.pref_id;
