-- 4f. Test suspect 1 — two rows, fully reversible
-- READ-ONLY
--
-- GENERATED from pref-setting-user-profile-test/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

SELECT
    ps.pref_category,
    ps.[pref_group#],
    ps.pref_id,
    ps.pref_data                        AS [current_value],
    CASE ps.pref_id
         WHEN 'rect' THEN '334,241,1630,1009'
         WHEN 'max'  THEN '0;0'
    END                                 AS [proposed_value]
FROM pref_setting ps
WHERE ps.user_id = 'CATALOGER'
  AND ps.pref_category = 'WRKSPC'
  AND ps.pref_id IN ('rect', 'max');
