-- 4f. Test suspect 1 — two rows, fully reversible
-- WRITES - review before running
--
-- GENERATED from pref-setting-user-profile-test/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

BEGIN TRANSACTION;

UPDATE pref_setting
SET    pref_data = CASE pref_id
                        WHEN 'rect' THEN '334,241,1630,1009'
                        WHEN 'max'  THEN '0;0'
                        ELSE pref_data
                   END
WHERE user_id = 'CATALOGER'
  AND pref_category = 'WRKSPC'
  AND pref_id IN ('rect', 'max');

SELECT @@ROWCOUNT AS [rows_updated];    -- must be 2

-- COMMIT TRANSACTION;
-- ROLLBACK TRANSACTION;
