-- 4f. Test suspect 1 — two rows, fully reversible
-- WRITES - review before running
--
-- GENERATED from pref-setting-user-profile-test/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

UPDATE pref_setting
SET    pref_data = CASE pref_id
                        WHEN 'rect' THEN '-1928,-8,-632,760'
                        WHEN 'max'  THEN '1;1'
                        ELSE pref_data
                   END
WHERE user_id = 'CATALOGER'
  AND pref_category = 'WRKSPC'
  AND pref_id IN ('rect', 'max');
