-- 2026-10-06 (later) — a regression, and why this is now the vendor's
-- READ-ONLY
--
-- GENERATED from pref-setting-user-profile-test/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Read-only. Expect 4 rows: basebar7, extbar7, max, rect.
-- image and istyle absent confirms the interface fix is intact and only the
-- image rows are missing.
SELECT ps.pref_category, ps.pref_id, ps.pref_data
FROM pref_setting ps
WHERE ps.user_id = 'CATALOGER'
  AND ((ps.pref_category = 'WRKSPC'  AND ps.pref_id IN ('rect','max','image','istyle'))
    OR (ps.pref_category = 'CTRLBAR' AND ps.pref_id IN ('basebar7','extbar7')))
ORDER BY ps.pref_category, ps.pref_id;
