-- Step 5: Clean up
-- WRITES - review before running
--
-- GENERATED from pref-setting-user-profile-test/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Remove the copied preferences once the test is concluded.
DELETE FROM pref_setting WHERE user_id = 'CATALOGER_T';
SELECT @@ROWCOUNT AS [rows_removed];
