-- 1a. Production — what is actually missing?
-- READ-ONLY
--
-- GENERATED from borrlegal-kw-restore/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Run in ILSDB (production).
-- Every table and column below was looked up in horizon-schema/, not inferred.
SELECT
    s.name                                AS [schema],
    o.name                                AS [object_name],
    o.type_desc                           AS [object_type],
    CONVERT(char(23), o.create_date, 121) AS [created]
FROM sys.objects o
INNER JOIN sys.schemas s ON s.schema_id = o.schema_id
WHERE o.name LIKE 'borrLegal%'
ORDER BY o.type_desc, o.name;
