-- 1b. Production — are they enabled?
-- READ-ONLY
--
-- GENERATED from borrlegal-kw-restore/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Run in ILSDB (production).
SELECT
    tr.name                   AS [trigger_name],
    OBJECT_NAME(tr.parent_id) AS [on_table],
    tr.is_disabled,
    tr.is_instead_of_trigger
FROM sys.triggers tr
WHERE tr.name LIKE 'borrLegal%'
ORDER BY tr.name;
