-- 1b. Production — are they enabled?
-- WRITES - review before running
--
-- GENERATED from borrlegal-kw-restore/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Only if 1b shows existing but disabled triggers. Run in ILSDB.
ENABLE TRIGGER [borrLegal_KW_i_trig] ON [dbo].[borrLegal_KW];
ENABLE TRIGGER [borrLegal_KW_u_trig] ON [dbo].[borrLegal_KW];
ENABLE TRIGGER [borrLegal_KW_d_trig] ON [dbo].[borrLegal_KW];
