-- 1c. Both databases — does the recreated table match the original?
-- READ-ONLY
--
-- GENERATED from borrlegal-kw-restore/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Run in BOTH ILSTRAINDB and ILSDB. Compare the outputs.
SELECT
    c.column_id,
    c.name            AS [column_name],
    ty.name           AS [type_name],
    ty.is_user_defined,
    c.max_length,
    c.precision,
    c.scale,
    c.is_nullable,
    c.is_identity
FROM sys.columns c
INNER JOIN sys.types ty ON ty.user_type_id = c.user_type_id
WHERE c.object_id = OBJECT_ID('dbo.borrLegal_KW')
ORDER BY c.column_id;
