-- 1c. Both databases — does the recreated table match the original?
-- READ-ONLY
--
-- GENERATED from borrlegal-kw-restore/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Run in BOTH ILSTRAINDB and ILSDB. Indexes carry the grain; a missing unique
-- index lets duplicate postings in, which is a silent correctness problem.
SELECT
    i.name        AS [index_name],
    i.type_desc,
    i.is_unique,
    i.is_primary_key,
    c.name        AS [column_name],
    ic.key_ordinal
FROM sys.indexes i
INNER JOIN sys.index_columns ic
        ON ic.object_id = i.object_id AND ic.index_id = i.index_id
INNER JOIN sys.columns c
        ON c.object_id = ic.object_id AND c.column_id = ic.column_id
WHERE i.object_id = OBJECT_ID('dbo.borrLegal_KW')
ORDER BY i.name, ic.key_ordinal;
