-- 1d. Source — do the trigger bodies depend on anything else that was dropped?
-- WRITES - review before running
--
-- GENERATED from borrlegal-kw-restore/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Run in ILSTRAINDB. Replace these with YOUR dropped object names.
DECLARE @Dropped TABLE (name sysname PRIMARY KEY);
INSERT INTO @Dropped (name) VALUES
 ('some_dropped_table'), ('another_dropped_table');

SELECT
    o.name AS [trigger_name],
    d.name AS [references_dropped_object]
FROM sys.sql_modules m
INNER JOIN sys.objects o ON o.object_id = m.object_id
INNER JOIN @Dropped d ON m.definition LIKE '%' + d.name + '%'
WHERE o.name LIKE 'borrLegal%'
ORDER BY o.name, d.name;
