-- 1d. Source — do the trigger bodies depend on anything else that was dropped?
-- READ-ONLY
--
-- GENERATED from borrlegal-kw-restore/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Run in ILSDB (production). The list-free version, and the better check:
-- what do the triggers reference that does not exist HERE, now? This catches
-- objects nobody remembered were dropped, which is the real risk.
--
-- Run it AFTER the triggers exist in production (after Step 2b) - an object
-- that is absent cannot have its references resolved.
SELECT
    OBJECT_NAME(d.referencing_id)  AS [trigger_name],
    d.referenced_entity_name       AS [missing_object]
FROM sys.sql_expression_dependencies d
WHERE OBJECT_NAME(d.referencing_id) LIKE 'borrLegal%'
  AND d.referenced_id IS NULL          -- unresolved = does not exist
  AND d.referenced_entity_name IS NOT NULL
ORDER BY [trigger_name], [missing_object];
