-- 1d. Source — do the trigger bodies depend on anything else that was dropped?
-- READ-ONLY
--
-- GENERATED from borrlegal-kw-restore/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Run in ILSTRAINDB. Encrypted modules have definition = NULL and CANNOT be
-- text-searched, so the check above has a blind spot if any exist. Note them.
SELECT o.name AS [encrypted_module], o.type_desc
FROM sys.sql_modules m
INNER JOIN sys.objects o ON o.object_id = m.object_id
WHERE m.definition IS NULL;
