-- 1e. Source — read the trigger bodies
-- WRITES - review before running
--
-- GENERATED from borrlegal-kw-restore/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Run in ILSTRAINDB. sp_helptext preserves line breaks; the sys.sql_modules
-- grid does not, and it truncates long definitions.
EXEC sp_helptext 'dbo.borrLegal_KW_i_trig';
EXEC sp_helptext 'dbo.borrLegal_KW_u_trig';
EXEC sp_helptext 'dbo.borrLegal_KW_d_trig';
