-- 1f. Production — is an object-level grant needed at all?
-- READ-ONLY
--
-- GENERATED from borrlegal-kw-restore/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Run in ILSDB. Substitute your real principal.
DECLARE @Principal sysname = 'staff_readers';

SELECT name, type_desc, is_fixed_role, default_schema_name
FROM sys.database_principals
WHERE name = @Principal;

-- Fixed-role membership covers every table automatically.
SELECT r.name AS [role_name], m.name AS [member_name]
FROM sys.database_role_members drm
INNER JOIN sys.database_principals r ON r.principal_id = drm.role_principal_id
INNER JOIN sys.database_principals m ON m.principal_id = drm.member_principal_id
WHERE m.name = @Principal
ORDER BY r.name;

-- Database-wide (class 0) and schema-wide (class 3) grants cover it too.
SELECT dp.class_desc, dp.permission_name, dp.state_desc,
       CASE dp.class WHEN 3 THEN SCHEMA_NAME(dp.major_id) ELSE '' END AS [on_schema]
FROM sys.database_permissions dp
WHERE dp.grantee_principal_id = DATABASE_PRINCIPAL_ID(@Principal)
  AND dp.class IN (0, 3)
ORDER BY dp.class, dp.permission_name;
