-- 1g. Source — generate the grants, do not invent them
-- READ-ONLY
--
-- GENERATED from borrlegal-kw-restore/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Run in ILSTRAINDB. This produces statements to run in ILSDB.
SELECT
    CASE dp.state_desc
         WHEN 'GRANT_WITH_GRANT_OPTION' THEN 'GRANT'
         ELSE dp.state_desc
    END
    + ' ' + dp.permission_name
    + CASE WHEN dp.minor_id <> 0
           THEN ' (' + QUOTENAME(COL_NAME(dp.major_id, dp.minor_id)) + ')'
           ELSE '' END
    + ' ON dbo.' + QUOTENAME(o.name)
    + ' TO ' + QUOTENAME(pr.name)
    + CASE WHEN dp.state_desc = 'GRANT_WITH_GRANT_OPTION'
           THEN ' WITH GRANT OPTION' ELSE '' END
    + ';'                                    AS [statement_to_run_in_prod],
    pr.name                                  AS [grantee],
    pr.type_desc                             AS [grantee_type]
FROM sys.database_permissions dp
INNER JOIN sys.objects o              ON o.object_id     = dp.major_id
INNER JOIN sys.database_principals pr ON pr.principal_id = dp.grantee_principal_id
WHERE dp.class = 1
  AND o.name = 'borrLegal_KW'
ORDER BY pr.name, dp.permission_name;
