-- 2c. Confirm
-- READ-ONLY
--
-- GENERATED from borrlegal-kw-restore/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Run in ILSDB. Expect four rows, and is_disabled = 0 on all three triggers.
SELECT o.name AS [object_name], o.type_desc
FROM sys.objects o
WHERE o.name LIKE 'borrLegal%'
ORDER BY o.type_desc, o.name;

SELECT tr.name AS [trigger_name], OBJECT_NAME(tr.parent_id) AS [on_table],
       tr.is_disabled
FROM sys.triggers tr
WHERE tr.name LIKE 'borrLegal%'
ORDER BY tr.name;
