-- Step 3: The Update — permissions
-- WRITES - review before running
--
-- GENERATED from borrlegal-kw-restore/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Run in ILSDB. Should now agree with 1g's list.
DECLARE @Check sysname = 'staff_readers';

EXECUTE AS USER = @Check;
    SELECT permission_name
    FROM fn_my_permissions('dbo.borrLegal_KW', 'OBJECT')
    ORDER BY permission_name;
REVERT;
