-- Step 4: Reconcile the keyword counters
-- READ-ONLY
--
-- GENERATED from borrlegal-kw-restore/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Run in ILSDB. READ-ONLY - it reports drift, it does not correct it.
-- Adjust kw.[word#] to the actual join column from 1c if it differs.
SELECT TOP 200
    w.[word#],
    w.word,
    w.n_borrLegalKW      AS [counter_says],
    kw.actual            AS [postings_actually_present],
    kw.actual - w.n_borrLegalKW AS [drift]
FROM dbo.word w
INNER JOIN (
        SELECT k.[word#], COUNT(*) AS actual
        FROM dbo.borrLegal_KW k
        GROUP BY k.[word#]
) kw ON kw.[word#] = w.[word#]
WHERE kw.actual <> w.n_borrLegalKW
ORDER BY ABS(kw.actual - w.n_borrLegalKW) DESC;
