-- Step 4: Reconcile the keyword counters
-- READ-ONLY
--
-- GENERATED from borrlegal-kw-restore/README.md by tools/Build-SolutionDocs.ps1.
-- Do not edit this file - edit the README and re-run the script.
-- The README carries the reasoning, review gates and caveats.

-- Run in ILSDB. The other direction: counter says there are postings, but none
-- exist. An INNER JOIN above cannot see these.
SELECT TOP 200 w.[word#], w.word, w.n_borrLegalKW AS [counter_says]
FROM dbo.word w
WHERE w.n_borrLegalKW <> 0
  AND NOT EXISTS (SELECT 1 FROM dbo.borrLegal_KW k WHERE k.[word#] = w.[word#])
ORDER BY w.n_borrLegalKW DESC;
